plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev'
}


// ==========================================================================
// MOD INFORMATION
// ==========================================================================

def modId = 'mantle'
def modName = 'Mantle'
def modVersion = '3.11.2'
def modGroup = 'slimeknights.mantle'
def modLicense = 'All Rights Reserved'


version = modVersion
group = modGroup


// ==========================================================================
// JAVA
// ==========================================================================

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}


// ==========================================================================
// JAR
// ==========================================================================

base {
    archivesName = modId
}

tasks.withType(Jar).configureEach {
    zip64 = true
}


// ==========================================================================
// RESOURCES
// ==========================================================================

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}


// ==========================================================================
// REPOSITORIES
// ==========================================================================

repositories {
    maven {
        name = 'BlameJared Maven'
        url = 'https://maven.blamejared.com'
    }
}


// ==========================================================================
// RUN CONFIGURATIONS
// ==========================================================================

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'

        workingDirectory project.layout.projectDirectory
                .dir('run')
                .dir(name)

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', modId
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', modId
        argument '--nogui'
    }

    gameTestServer {
        systemProperty 'neoforge.enabledGameTestNamespaces', modId
    }

    data {
        arguments.addAll(
                '--mod', modId,
                '--all',
                '--output',
                file('src/generated/resources/').absolutePath,
                '--existing',
                file('src/main/resources/').absolutePath
        )
    }
}


// ==========================================================================
// CONFIGURATIONS
// ==========================================================================

configurations {
    runtimeClasspath.extendsFrom localRuntime
}


// ==========================================================================
// DEPENDENCIES
// ==========================================================================

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"

    localRuntime "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
}


// ==========================================================================
// RESOURCE EXPANSION
// ==========================================================================

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            loader_version_range    : loader_version_range,

            mod_id                  : modId,
            mod_name                : modName,
            mod_license             : modLicense,
            mod_version             : modVersion
    ]

    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}


// ==========================================================================
// PUBLISHING
// ==========================================================================

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}